version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=answering_bot_db
      - DB_USER=postgres
      - DB_PASSWORD=rootroot
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: answering_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
